# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("journal", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        )
    ]
