# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
