# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 01:52
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [("journal", "0003_auto_20170922_2148")]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="position",
            field=geoposition.fields.GeopositionField(max_length=42),
        )
    ]
