# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170922_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['modified_at']},
        ),
    ]
