# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20170922_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-modified_at']},
        ),
    ]
