# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("journal", "0006_auto_20170922_2346")]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="image",
            field=models.ImageField(null=True, upload_to="static/media/"),
        )
    ]
