# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20171009_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
