# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("journal", "0010_auto_20171011_2036")]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="image",
            field=models.ImageField(null=True, upload_to="media/"),
        )
    ]
