# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20171011_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='position',
        ),
    ]
