# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_remove_journal_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='is_draft',
        ),
    ]
