# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("journal", "0015_journal_is_draft")]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="location",
            field=models.CharField(max_length=50, null=True),
        )
    ]
