# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_journal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
