# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("journal", "0018_tag")]

    operations = [
        migrations.RemoveField(model_name="tag", name="journal"),
        migrations.DeleteModel(name="Tag"),
    ]
