# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("userprofile", "0003_auto_20171016_2035")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="\\profile_pic"),
        )
    ]
